"""
compare_regression_models.py – Combine fair and rubric-assisted metrics into a report.

Reads:
    data/processed/fair_regression_model_metrics.csv
    data/processed/rubric_assisted_regression_model_metrics.csv

Writes:
    data/processed/model_metrics_report.csv
    docs/reports/model_metrics_summary.md

Run from the backend directory:
    python -m app.compare_regression_models
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
PROCESSED_DIR = REPO_ROOT / "data" / "processed"
DOCS_REPORTS_DIR = REPO_ROOT / "docs" / "reports"

FAIR_METRICS_FILE = PROCESSED_DIR / "fair_regression_model_metrics.csv"
RUBRIC_METRICS_FILE = PROCESSED_DIR / "rubric_assisted_regression_model_metrics.csv"
REPORT_FILE = PROCESSED_DIR / "model_metrics_report.csv"
SUMMARY_FILE = DOCS_REPORTS_DIR / "model_metrics_summary.md"
SPLIT_SUMMARY_FILE = PROCESSED_DIR / "regression_split_summary.json"

REQUIRED_COLUMNS = [
    "track", "model", "mae", "rmse", "r2",
    "precision_at_1", "precision_at_3", "precision_at_5",
    "train_rows", "test_rows", "train_profiles", "test_profiles",
    "feature_set", "leakage_safe",
]


def load_metrics(path: Path, label: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"{label} metrics not found at {path}. "
            f"Run the corresponding training script first."
        )
    df = pd.read_csv(path)
    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"{label} metrics missing columns: {missing}")
    return df


def combine_metrics(fair_df: pd.DataFrame, rubric_df: pd.DataFrame) -> pd.DataFrame:
    """Merge both tracks; fair first, then rubric-assisted, each sorted by MAE."""
    fair_sorted = fair_df.sort_values("mae").reset_index(drop=True)
    rubric_sorted = rubric_df.sort_values("mae").reset_index(drop=True)
    combined = pd.concat([fair_sorted, rubric_sorted], ignore_index=True)
    return combined[REQUIRED_COLUMNS]


def _best_row(df: pd.DataFrame) -> pd.Series:
    return df.sort_values("mae").iloc[0]


def _load_split_summary() -> Optional[dict]:
    if SPLIT_SUMMARY_FILE.exists():
        with open(SPLIT_SUMMARY_FILE, encoding="utf-8") as f:
            return json.load(f)
    return None


def build_summary_markdown(combined: pd.DataFrame) -> str:
    """Generate a concise model_metrics_summary.md."""
    fair = combined[combined["track"] == "fair"]
    rubric = combined[combined["track"] == "rubric_assisted"]

    best_fair = _best_row(fair) if not fair.empty else None
    best_rubric = _best_row(rubric) if not rubric.empty else None

    split = _load_split_summary()

    lines: list[str] = []
    lines.append("# ML-3 Regression Model Metrics Summary")
    lines.append("")
    lines.append(
        "Generated by `compare_regression_models.py`. "
        "See `data/processed/model_metrics_report.csv` for full table."
    )
    lines.append("")

    # --- Dataset / split ---
    lines.append("## Dataset and Split")
    lines.append("")
    if split:
        lines.append(f"- **Total rows:** {split['total_rows']:,}")
        lines.append(f"- **Train rows:** {split['train_rows']:,} ({split['train_ratio']*100:.1f}%)")
        lines.append(f"- **Test rows:** {split['test_rows']:,} ({split['test_ratio']*100:.1f}%)")
        lines.append(f"- **Total profiles:** {split['total_profiles']}")
        lines.append(f"- **Train profiles:** {split['train_profiles']}")
        lines.append(f"- **Test profiles:** {split['test_profiles']}")
        lines.append(f"- **Split method:** {split['split_method']} by `profile_id`")
        lines.append(
            "- **Profile overlap:** None — no `profile_id` appears in both train and test."
        )
    else:
        lines.append("- Split summary not available (run `inspect_regression_split.py`).")
    lines.append("")

    # --- Best fair model ---
    lines.append("## Best Fair Model (Track A — leakage-safe)")
    lines.append("")
    lines.append(
        "These models use only realistic input features "
        "(text, categoricals, counts). Rubric component scores are excluded."
    )
    lines.append("")
    if best_fair is not None:
        lines.append(f"- **Model:** `{best_fair['model']}`")
        lines.append(f"- **MAE:** {best_fair['mae']:.4f}")
        lines.append(f"- **RMSE:** {best_fair['rmse']:.4f}")
        lines.append(f"- **R²:** {best_fair['r2']:.4f}")
        lines.append(f"- **Precision@1:** {best_fair['precision_at_1']:.4f}")
        lines.append(f"- **Precision@3:** {best_fair['precision_at_3']:.4f}")
        lines.append(f"- **Precision@5:** {best_fair['precision_at_5']:.4f}")
        lines.append(f"- **Feature set:** `{best_fair['feature_set']}`")
        lines.append(f"- **Leakage-safe:** `{best_fair['leakage_safe']}`")
    else:
        lines.append("- No fair metrics available.")
    lines.append("")

    # --- All fair models table ---
    if not fair.empty:
        lines.append("### All Fair Models")
        lines.append("")
        lines.append(
            "| Model | MAE | RMSE | R² | P@1 | P@3 | P@5 |"
        )
        lines.append(
            "|---|---|---|---|---|---|---|"
        )
        for _, row in fair.iterrows():
            lines.append(
                f"| `{row['model']}` "
                f"| {row['mae']:.4f} "
                f"| {row['rmse']:.4f} "
                f"| {row['r2']:.4f} "
                f"| {row['precision_at_1']:.4f} "
                f"| {row['precision_at_3']:.4f} "
                f"| {row['precision_at_5']:.4f} |"
            )
        lines.append("")

    # --- Best rubric-assisted model ---
    lines.append("## Best Rubric-Assisted Model (Track B — leakage demo)")
    lines.append("")
    lines.append(
        "These models use rubric component scores "
        "(`major_fit_score`, `skill_match_score`, …) as features. "
        "Because `target_score` is a weighted sum of those same components, "
        "the metrics are **unrealistically strong** and must NOT be presented "
        "as honest model performance."
    )
    lines.append("")
    if best_rubric is not None:
        lines.append(f"- **Model:** `{best_rubric['model']}`")
        lines.append(f"- **MAE:** {best_rubric['mae']:.4f}")
        lines.append(f"- **RMSE:** {best_rubric['rmse']:.4f}")
        lines.append(f"- **R²:** {best_rubric['r2']:.4f}")
        lines.append(f"- **Precision@5:** {best_rubric['precision_at_5']:.4f}")
        lines.append(f"- **Feature set:** `{best_rubric['feature_set']}`")
        lines.append(f"- **Leakage-safe:** `{best_rubric['leakage_safe']}`")
    else:
        lines.append("- No rubric-assisted metrics available.")
    lines.append("")

    # --- Why rubric-assisted is not the honest model ---
    lines.append("## Why Rubric-Assisted Is Not the Honest Model")
    lines.append("")
    lines.append(
        "The `target_score` label is defined as a weighted linear combination of "
        "eight rubric component scores "
        "(`major_fit_score`, `skill_match_score`, `role_interest_score`, "
        "`city_match_score`, `program_type_score`, `work_mode_score`, "
        "`verification_score`, `interview_score`). "
        "When those same eight values are included as model features, "
        "any regressor can reconstruct `target_score` almost perfectly by learning "
        "the linear weights — resulting in near-zero MAE and R² ≈ 1.0. "
        "This is **target leakage**, not genuine generalisation."
    )
    lines.append("")
    lines.append(
        "The fair models (Track A) exclude all rubric components and must predict "
        "`target_score` from raw student profile text and opportunity metadata alone. "
        "Their lower R² reflects honest uncertainty, not poor engineering."
    )
    lines.append("")

    # --- Artifacts ---
    lines.append("## Artifacts")
    lines.append("")
    lines.append("| Artifact | Path |")
    lines.append("|---|---|")
    artifacts = [
        ("Fair Ridge pipeline", "models/fair_ridge_model.joblib"),
        ("Fair Random Forest pipeline", "models/fair_random_forest_model.joblib"),
        ("Fair Gradient Boosting pipeline", "models/fair_gradient_boosting_model.joblib"),
        ("Rubric-assisted Ridge pipeline", "models/rubric_assisted_ridge_model.joblib"),
        ("Rubric-assisted RF pipeline", "models/rubric_assisted_random_forest_model.joblib"),
        ("Rubric-assisted GB pipeline", "models/rubric_assisted_gradient_boosting_model.joblib"),
        ("Fair metrics CSV", "data/processed/fair_regression_model_metrics.csv"),
        ("Fair predictions CSV", "data/processed/fair_regression_predictions.csv"),
        ("Rubric-assisted metrics CSV", "data/processed/rubric_assisted_regression_model_metrics.csv"),
        ("Rubric-assisted predictions CSV", "data/processed/rubric_assisted_regression_predictions.csv"),
        ("Combined report CSV", "data/processed/model_metrics_report.csv"),
        ("Prediction vs actual plot (fair)", "reports/figures/fair_regression_prediction_vs_actual.png"),
    ]
    for name, path in artifacts:
        lines.append(f"| {name} | `{path}` |")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    DOCS_REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    print("[compare_regression_models] Loading metrics …")
    fair_df = load_metrics(FAIR_METRICS_FILE, "fair")
    rubric_df = load_metrics(RUBRIC_METRICS_FILE, "rubric_assisted")

    combined = combine_metrics(fair_df, rubric_df)
    combined.to_csv(REPORT_FILE, index=False)
    print(f"[compare_regression_models] Combined report saved to {REPORT_FILE}")

    # Print summary table
    print("\n=== Combined Model Metrics Report ===")
    display_cols = ["track", "model", "mae", "rmse", "r2", "precision_at_5", "leakage_safe"]
    print(combined[display_cols].to_string(index=False))

    fair = combined[combined["track"] == "fair"]
    rubric = combined[combined["track"] == "rubric_assisted"]

    if not fair.empty:
        best_fair = _best_row(fair)
        print(
            f"\nBest fair model: {best_fair['model']} "
            f"(MAE={best_fair['mae']:.3f}, R²={best_fair['r2']:.3f}) — leakage-safe=True"
        )
    if not rubric.empty:
        best_rubric = _best_row(rubric)
        print(
            f"Best rubric-assisted: {best_rubric['model']} "
            f"(MAE={best_rubric['mae']:.3f}, R²={best_rubric['r2']:.3f}) — leakage-safe=False (DEMO ONLY)"
        )

    summary_md = build_summary_markdown(combined)
    SUMMARY_FILE.write_text(summary_md, encoding="utf-8")
    print(f"\n[compare_regression_models] Summary saved to {SUMMARY_FILE}")


if __name__ == "__main__":
    main()
